### ISSUE TITLE
switching

### ISSUE THREAD

**Issue by Qiang1991** [alistairewj/peak-detector#2]
why didn't you use ppg or sv in switching?

**Comment by jbehar** [comment]
You could. We used ECG and ABP only because the database that was provided for the Challenge had ECG systematically and ABP most of the time. Including PPG or SV could improve but because of the run time constraint (i.e. there was a timeout for running the algorithm on the Physionet server) we chose the signals that were the most reliable and most available i.e. ECG and ABP.
